### ISSUE TITLE
Subscriptiondetails property must and radio button have no red border

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#14]
Subscriptiondetails with property as radiobutton and is must don't have red boarder.

![grafik](https://user-images.githubusercontent.com/41326409/49635055-ce1fcc80-f9fe-11e8-8c0d-050ad32fe034.png)

**Comment by cravay** [comment]
ready for testing

**Comment by schefbi** [comment]
Tested works.
![grafik](https://user-images.githubusercontent.com/41326409/51730543-1d39c380-2078-11e9-9a9c-2e73460d1997.png)
