### ISSUE TITLE
validierung und helper funktion für SocialSecurityNumber

### ISSUE THREAD

**Issue by cravay** [erz-mba-fbi/kursausschreibung#15]
Validierung und helper funktion für SocialSecurityNumber. 

**Helper:** 
- event KeyUp nur Zahlen eingeben 
- An den Stelle 4, 9, 14 das Punkt automatisch machen.

**Validierung:** 
- nnn.nnnn.nnnn.nn

**Comment by cravay** [comment]
@schefbi Kannst du bitte auf dem Dev-Server ein Event mit dem SubscriptionDetail für AHV-Nummber einrichten?

**Comment by schefbi** [comment]
@cravay Das ist eine Eigenschaft im /Persons/ model `SocialSecurityNumber`.

**Comment by schefbi** [comment]
Wiki dokumentiert.
