### ISSUE TITLE
Default Setting persons model (CountryId)

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#24]
Im Settings.js sollen default Persons model eigenschaften erstellt werden können. 
Wenn diese eigenschaften im Persons model null sind sollen  die default eigenschaften übermittelt werden.

**bsp.** 

```
//fields they are not in form or not required, you can set a default value. it will be overwrite null value in persons modell
"personDefaultValue": {
"CountryId": "CH",
}
```

**Comment by cravay** [comment]
Ich habe es so umgesetzt.   

Ich habe jetzt eine branch für die Entwicklung erstellt, der build kann aber genau gleich heruntergeladen werden.

**Comment by schefbi** [comment]
Test Ok
