### ISSUE TITLE
moduleRedirectUrl funktioniert nicht in jedem Fall

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#25]
Rückmeldung Comvation:
Wir haben das Problem analysiert. Das Problem kommt aus dem Plugin "kursausschreibung.js".
Dort ist ein Bug: Die Redirect-URL nach der Authentifizierung auf der REST-Api wird leider per history.replaceState in die Adresszeile geschrieben.
Das führt dazu, dass der Webserver keine neue Anfrage vom Browser bekommt (weil neue Adresse nur im Browser geändert wurde).
Die neue URL wird nur mit folgendem Befehl zum Webserver geschickt: "document.location.href = URL".

**Bugfix**
```
/* Customizing Comvation: Only rewrite history with "replaceState" when script run on plugin page. On all other pages (when token authentification go to startpage) use document.location.href */ 
 jQuery('#kursausschreibung-root').length > 0 ? (history.replaceState(null, null, (0,a.getParameterByName)("moduleRedirectUrl"))) : (document.location.href = (0,a.getParameterByName)("moduleRedirectUrl"));
 /*history.replaceState(null, null, (0, a.getParameterByName)("moduleRedirectUrl"))*/
```

Jetzt funktionieren auch externe Links. Bsp.:
http://www.bffbern.ch/de/Weiterbildung/Betriebliche-Bildung-und-Beratung/Weiterbildung-fuer-Berufsbildnerinnen-und-Berufsbildner/Info#/weiterbildung/kurs%20wb%20erziehung%2Fsoziales/53718

**Comment by cravay** [comment]
Ich verstehe den Bug-Report nicht ganz. Wenn der Browser vom OAuth-Server weitergeleitet wird, wird ein Request zum Server gemacht. `history.replaceState` wird lediglich dazu verwendet, um die Tokens aus der URL zu entfernen.

Verstehe ich etwas falsch? Könntest du mir ev. den gesamten Bugreport weiterleiten?

Wenn ich mich richtig erinnere wurde in der Vorlage von CLX `window.location.replace` verwendet. Ich glaube das habe ich dann ersetzt, weil du mich darauf hingewiesen hast, dass das Modul unnötig neu geladen wurde.

**Comment by schefbi** [comment]
Ich habe mir das ganze nochmals angeschaut und denke wir lösen das Problem besser ausserhalb des Moduls. 

Was meinst du zu diesem Vorschlag. Bei der Integration des Moduls auf einer Seite soll auf der Masterpage (CMS) folgender Script integriert werden. Somit ist sichergestellt, falls das Modul aufeine andere unterseite verschoben wird und noch kein Token vorhanden ist, dass immer an die richtige Route weitegleitet wird.

```
var url = window.location.href;
if (url.indexOf('?') > 0) {

var urlParameters = url.split('?');
var redirectURL = getParameterByName('moduleRedirectUrl')
    if (urlParameters[1].indexOf("access_token") > -1) {
    window.location = redirectURL + '?' + urlParameters[1];

    } 
}

/**
 * get an URL-parameter
 * taken from https://stackoverflow.com/q/901115#answer-901144
 * @param {string} name the name of the parameter
 * @param {string} url the URL (defaults to current URL)
 */
function getParameterByName(name, url) {

if (typeof url !== 'string') {
  url = window.location.href;
}

name = name.replace(/[[\]]/g, '\\url');

var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)');
var results = regex.exec(url);

if (!results) {
  return null;
}

if (!results[2]) {
  return '';
}

return decodeURIComponent(results[2].replace(/\+/g, ' '));
}
```

**Comment by cravay** [comment]
Das hört sich gut an.
