### ISSUE TITLE
PUT /Persons/{idPerson} 409 > Sie sind nicht berechtigt, im Feld \"Firmazeile 1\" einen Wert zu erfassen.

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#26]
Workaround implementieren, falls beim PUT `/Persons/{idPerson}` ein 409 mit der Message "Firmazeile 1" oder "Ligne entreprise 1" zurückkommt. Wird nicht abgebrochen und die Anmeldung wird ohne Änderung der Personendaten erfolgen.

**409 Conflict**
```
{
    "HasErrors": true,
    "HasQuestions": false,
    "Issues": [
        {
            "Id": null,
            "Message": "Sie sind nicht berechtigt, im Feld \"Firmazeile 1\" einen Wert zu erfassen.",
            "MessageId": null,
            "MessageType": "Error",
            "Property": null
        }
    ]
}
```

**Comment by schefbi** [comment]
**Testkurs**
https://mba-fbi.zubler.ch/modultest/FBI/veranstaltung.html#/ausbildung/fbi-event

**Testdaten**
Meine Vorname, Nachname E-Mail Geschäft (Geburtsdatum ist nicht relevant)

**Comment by cravay** [comment]
Kann ich es auch so umsetzen, dass alle Fehler auf `PUT /Persons/` ignoriert werden? Ich würde mich lieber nicht darauf verlassen, dass eine Fehlermeldung einen bestimmten Wert enthält.

**Comment by schefbi** [comment]
Ja, das kannst du. Wir können eigentlich in jedem Fall eine Anmeldung machen bei einem PUT.

Von: Michael Schertenleib <notifications@github.com>
Gesendet: Dienstag, 19. März 2019 23:13
An: erz-mba-fbi/kursausschreibung <kursausschreibung@noreply.github.com>
Cc: Scheidt Sandro, ERZ-MBA-FBI <sandro.scheidt@erz.be.ch>; Author <author@noreply.github.com>
Betreff: Re: [erz-mba-fbi/kursausschreibung] PUT /Persons/{idPerson} 409 > Sie sind nicht berechtigt, im Feld \"Firmazeile 1\" einen Wert zu erfassen. (#26)


Kann ich es auch so umsetzen, dass alle Fehler auf PUT /Persons/ ignoriert werden? Ich würde mich lieber nicht darauf verlassen, dass eine Fehlermeldung einen bestimmten Wert enthält.

**Comment by cravay** [comment]
Im neusten build auf dem develop-branch sollten jetzt Fehler bei `PUT /Persons/` ignoriert werden. Ich war aber noch nicht in der Lage es zu testen.

**Comment by schefbi** [comment]
Test Ok.
