### ISSUE TITLE
Feature idea: Introduce "Permalink"

### ISSUE THREAD

**Issue by ursbraem** [erz-mba-fbi/kursausschreibung#29]
While the URL of a course detail can change all the time, I would propose to add a "permalink" option that can be shared. All this needs is the UID of the course. 

So something like `https://www.bzemme.ch/kurseweiterbildung/#/uid/36315`

Would redirect to `https://www.bzemme.ch/kurseweiterbildung/#/weiterbildung/holzbau%20(wb)/36315`

but if the category is renamed or changed

`https://www.bzemme.ch/kurseweiterbildung/#/weiterbildung/modellbau%20(wb)/36315`

the first URL would still work fine.

**Comment by ursbraem** [comment]
Another plus is that with a single redirect rule on the server, even shorter URLs could be created for print publishing, like

`https://www.bzemme.ch/kurse/36315`

**Comment by cravay** [comment]
@schefbi kann ich das so umsetzen?

**Comment by schefbi** [comment]
@cravay Ja du kannst. Bitte anschliessend im wiki dokumentieren.

**Comment by cravay** [comment]
Ich habe die Route implementiert und im Wiki unter *Content design* eine Bemerkung hinzugefügt.

**Comment by schefbi** [comment]
Testing OK. Im Wiki wurde noch die Raute hinzugefügt `#/uid/{{eventId}}`.

**Comment by ursbraem** [comment]
Oh, wunderbar!
