### ISSUE TITLE
Enhancement: Anchor jumps

### ISSUE THREAD

**Issue by ursbraem** [erz-mba-fbi/kursausschreibung#31]
When applying for a course (Chrome on mac)

* on the first click ("Anmelden") the page jumps to the page top instead of to the opened form
* on the second click ("Anmelden") the page jumps to the bottom instead of to the thank you message

So users are lost twice. Maybe this depends on the used layout. But I think it would make sense to scroll/jump to where the next thing is after an action.

I'm not sure, but maybe this is a start? https://stackoverflow.com/a/23034716/160968

**Comment by schefbi** [comment]
scrollIntoView must be better solved. I suggest the following. We have to solve that per route.

**Route change**
- `area_of_education` no scrollIntoView
- `category` no scrollIntoView
- `event_id` scrollIntoView to top of event
- `subscribe` scrollIntoView to top of subscribe-form
- `confirmation` scrollIntoView to top of thank you message

**Option scrollIntoView**
```
{
    behavior: 'smooth',
    block: 'start'
  }
```

**Comment by cravay** [comment]
I agree that the anchor jumps need to be reworked and I'll apply the fix provided by the answer on stackoverflow.

>`area_of_education` no scrollIntoView
>`category` no scrollIntoView

What's the reasoning behind this? I'd prefer to keep the current strategy for these routes.
I think the module should scroll to the top when a user is on the bottom of an event-list page and 
goes to the next page.

What does `scrollIntoView.block` do?

**Comment by schefbi** [comment]
Folgende 2 Änderungen wurden umgesetzt.

- `scrollIntoView({behavior: 'smooth'})`
- `subscribe` scrollIntoView to top of `subscriptionForm`
