### ISSUE TITLE
Neuer Status Garantierte Durchführung

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#32]
Es soll ein neuer Status aufgenommen werden. 

**Bedingung** 
wie `Green` plus zusätzlich `(MaxParticipants-FreeSeats) >= MinParticipants`

**Legende** 
`background-color: chartreuse;`
![grafik](https://user-images.githubusercontent.com/41326409/55246267-29432c80-5245-11e9-926b-d991b1b9025f.png)

**eventlist & detail**
![grafik](https://user-images.githubusercontent.com/41326409/55246638-e766b600-5245-11e9-8362-accd10b96638.png)

**Comment by cravay** [comment]
umgesetzt

**Comment by schefbi** [comment]
Testing OK
