### ISSUE TITLE
Sprung zu Anker bei URL-Aufruf vermeiden

### ISSUE THREAD

**Issue by ursbraem** [erz-mba-fbi/kursausschreibung#41]
Bei Aufruf einer Kurs-URL springt die Seite automatisch in den Content. Je nach Layout (Fixe Bereiche) bewirkt das dann eine Überlappung (. Die User_innen müssen dann hochscrollen, um herauszufinden, wo sie gelandet sind.

Beispiele mit der v2 (aber bei v3 ist es auch, aber ist bei uns noch nicht live)

* https://www.bffbern.ch/weiterbildung-und-kurse/weiterbildung/weiterbildungskurse#/weiterbildung
* https://www.bffbern.ch/weiterbildung-und-kurse/weiterbildung/weiterbildungskurse#/weiterbildung/wb%20zebra/50998

Lässt sich dieser Sprung zum Inhalt deaktivieren? Wäre für uns hilfreich, sehe auch keinen Mehrwert darin.

**Comment by schefbi** [comment]
@ursbraem `scrollIntoView` macht sicher Sinn z.B. wir auf die 2 Seite der Eventlist gewechselt wird wieder an den Anfang gescrollt oder der/die Intressent/in ist beim einem der letzten Kurse auf der Liste und klickt die Details an. `scrollIntoView` bringt den/die Intressent/in an Start der Events. Bei der Implementation der BFF ist das Problem, dass Sie ein Sticky Header haben. Das führt dazu das der Content dann immer hinter dem Header ist. 

Folgende 3 Lösungen sehe ich um dieses Problem zu lösen.

1. Sie entfernen `scrollIntoView` im `kursauschreibung.js`
2. Wir erstellen in Zukunft ein Seeting `scrollIntoView: true/false`  
3. Sie überschreiben `scrollIntoView` nach dem laden des contents auf Ihren beliebigen Punkt

**Comment by ursbraem** [comment]
Danke! 

* Ist es auch möglich, `scrollIntoView` nur beim 1. Schritt zu deaktivieren?
* Oder könnten wir das Problem mit dem sticky header aus Ihrer Sicht auch mit einem CSS offset lösen (mein Kollege sagt, wird kompliziert)

**Comment by schefbi** [comment]
Nein, momentan kann nur überall, ausser `subscription route` die `ScrollIntoView` enfernt werden.

Sie können evtl. folgendes für den offset probieren. Wir werden schauen das wir in Zukunft ein seeting erstellen für den offset z.B. `scrollToOffset: 100` @cravay Was meinst du lässt sich das umsetzten?
```
var element = document.getElementById('kursausschreibung-root');
var headerOffset = 115;
var elementPosition = element.getBoundingClientRect().top;
var offsetPosition = elementPosition - headerOffset;
      
window.scrollTo({
          top: offsetPosition,
          behavior: "smooth"
      });  
```

**Comment by ursbraem** [comment]
Pixelangaben für den Offset: das ist eben das Problem mit dem Responsive Webdesign – die sind je nach Viewport ganz unterschiedlich. Ich glaub wir könnten die sonst auch im CSS machen, aber das ist leider auch dort knifflig.

**Comment by schefbi** [comment]
Wiki dokumentiert
