### ISSUE TITLE
Frage zur Kurz-URL mit ID

### ISSUE THREAD

**Issue by ursbraem** [erz-mba-fbi/kursausschreibung#42]
Das offizielle Muster für die Kurzlinks mit ID ist `path/to#/uid/123`. 

Wird `path/to/#/uid/123` auch unterstützt? Ich finde das symmetrischer und dadurch verständlicher. Bei mir (Chrome, Mac) hat es funktioniert.

**Comment by cravay** [comment]
Für Ember.js kommt es nicht darauf an, ob am Ende des URL-Pfades ein `/` steht oder nicht. Wichtig ist einfach, dass der Webserver die richtige Seite zurückliefert.

URLs der Form `.../path/to/#/uid/123` sollten problemlos verwendet werden können.

**Comment by ursbraem** [comment]
Danke!
