### ISSUE TITLE
Cosmetics: uniform indentation for the second line (eventlist, legend card)

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#5]
The traffic light symbol and the title of the event with uniform indentation for the second line. Same for legend card.
![grafik](https://user-images.githubusercontent.com/41326409/46061096-c376ca80-c165-11e8-9841-0f058807be2a.png)

![grafik](https://user-images.githubusercontent.com/41326409/46061152-02a51b80-c166-11e8-9945-20dc242b5dd9.png)

**Comment by cravay** [comment]
umgesetzt

**Comment by schefbi** [comment]
Bitte auch auf "event-details" umsetzten.
![grafik](https://user-images.githubusercontent.com/41326409/56567880-1dcdf180-65b6-11e9-9c06-142aee232d8a.png)
