### ISSUE TITLE
FATAL error while initializing the module:  TypeError: "event is null"

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#50]
Fehler beim laden des Moduls.

FATAL error while initializing the module:  TypeError: "event is null"
    events store.js:193
    filterEvents store.js:193
    init store.js:58
    tryCatcher rsvp.js:215
    invokeCallback rsvp.js:393
    publish rsvp.js:379
    <anonymous> Ember
    invoke backburner.js:205
    flush backburner.js:125
    flush backburner.js:278
    end backburner.js:410
    _boundAutorunEnd backburner.js:372

**Comment by schefbi** [comment]
@cravay: Kannst du dir das Modul mal auf der Testumgebung anschauen? Wir haben da einen Fehler mit dem neuen Release.

**Comment by cravay** [comment]
@schefbi Das Problem scheint zu sein, dass in den Antwort-Arrays von `GET /Events/` und `GET /EventLocations/` neu `null`-Werte enthalten sind. Ich konnte das Problem umgehen, indem ich sie herausgefiltert habe:

```diff
diff --git a/app/framework/store.js b/app/framework/store.js
index f7e6098..e4afde8 100644
--- a/app/framework/store.js
+++ b/app/framework/store.js
@@ -59,6 +59,15 @@ export function init() {
     getEventTexts(language)
   ]).then(function ([events, lessons, eventLocations, eventTexts]) {

+    // remove null-values (temporary fix, see #50)
+    let removeNull = array => array.filter(element => element !== null);
+    
+    events = removeNull(events);
+    lessons = removeNull(lessons);
+    eventLocations = removeNull(eventLocations);
+    eventTexts = removeNull(eventTexts);
+
     // filter events
     events = filterEvents(events, language);
```
Ich würde bei CLX einen Bug-Report machen. Ich glaube nicht, dass dieses Verhalten gewollt ist.

Sollte kursausschreibung mal zu Angular/Typescript portiert werden, würde es sicherlich Sinn ergeben, die Antworten wie im Modul absenzenmanagement zur Laufzeit zu überprüfen. Der jetzige Ansatz ist
etwas fragil.

**Comment by schefbi** [comment]
@cravay Merci für deine Analyse. Ich habe ein Bug bei CLX erfasst. Ich habe noch viele andere Fehler in diesem Release in der API entdeckt.
Ich melde mich wieder bei dir wenn bei uns wieder ein wenig Ruhe eingekehrt ist. Momentan hat der R1 und das Absenzenmanagement das durch Puzzle entwickelt wird Vorrang.

**Comment by schefbi** [comment]
Wurde in 2019.R1 durch CLX behoben.
