### ISSUE TITLE
PUT /Person/{id} 409 Mit der angegebenen PLZ muss der Ort wie folgt heissen: Bern

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#53]
CLX hat mit dem neuen Release eine Valideirung eingebaut die bei erfassen Person die PLZ und der eingegeben Ort Name mit den Evento Daten verglecht wenn diese nicht identisch sind wird folgende 409 beim `PUT /Persons/` zurückgemeldet.

**Request Body**
```
{
	"FormOfAddress": "Herr",
	"FormOfAddressId": 105,
	"Email2": "sandro.scheidt@swissonline.ch",
	"FirstName": "Sandro",
	"LastName": "Scheidt",
	"Location": "Bern qe4t",
	"Zip": "3006",
	"Id": 38381
}
```

**Response Body**
```
{"HasErrors":true,"HasQuestions":false,"Issues":[{"ConflictingObject":null,"ConflictingObjectType":null,"Id":null,"Message":"Mit der angegebenen PLZ muss der Ort wie folgt heissen: Bern","MessageId":null,"MessageType":"Error","Property":null}]}
```

**Solution**
onfocus event in subscribe-form eingebaut.
- Wird im input Feld (name=Zip) ein PLZ gefunden
- Wird im input Feld (name=Location) eine `datalist` mit den zum PLZ zugehörigen Orte drgestellt.

**settings.js**
formfields id=Location datalist konfigurieren bsp.
```
{
   "id": "Location",
   "dataType": "string",
   "options": { "required": true, "autocomplete": "address-level2", "datalist": "locationCodes" }
}
```

**Comment by cravay** [comment]
@schefbi Es kommt darauf an, was die Anforderungen von eurer Seite her sind. Wenn die alte Adresse behalten werden sollte, können wir 409-Antworten weiterhin ignorieren und nichts am Code ändern.

Wenn eine Fehlermeldung angezeigt werden sollte, müssen wir wohl oder übel die Fehlermeldung parsen.

**Comment by schefbi** [comment]
@cravay Das Problem ist das sich die Personen die als Duplikat erkannt wurden nicht mehr am Kurs anmelden können, weil die PLZ nicht zum Ort passt. Wir müssen das ihrgendwie lösen.

Wäre ein möglichkeit die Meldung zu parsen und dem Benutzer auf "/subscribe" Route anzuzeigen, damit er nur den Ort anpassen kann?

**Comment by cravay** [comment]
Gut, dass du eine Lösung gefunden hast!
