### ISSUE TITLE
Kursdaten als JSON o.ä. erhältlich?

### ISSUE THREAD

**Issue by ursbraem** [erz-mba-fbi/kursausschreibung#78]
Für die Publikation der Eventokurse auf eine zusätzliche externe Plattform (weiterbildung.swiss) möchten wir die Daten aufbereiten, um sie an die externe Schnittstelle weiterzureichen.

Das können wir gut machen, aber wie kommen wir an die Liste der Kurse, wenn wir "nur" das JS-Modul nutzen, nicht aber die REST-Schnittstelle?

Da die Rohdaten auch im JS-Modul stets vorhanden sind (ich sehe sie ja im Inspector), habe ich mir überlegt, ob es möglich wäre, dass diese auch via JS-Modul zur Weiterverarbeitung bezogen werden können. Ginge das? Oder ist das zu sehr um die Ecke gedacht?

Sonst müssen wir die Kurse (Liste/Detail) halt trotzdem per REST auslesen. 

Was halten Sie für sinnvoller?

**Comment by schefbi** [comment]
Ich denke das einfachste ist wenn Sie direkt auf die Rest API zugreifen. Denn es kann sein das die BFF nicht alle Kurs auf Weiterbildung.swiss Plattform haben möchte. Oder wie stellen Sie sich den Zugriff vor? Wenn z.B. auf die Route `/#getJsonData` zugegriffen wird werden alle Events gemäss `settings.js` angezeigt oder alle ohne Rücksicht auf ein Konfiguration?

**Comment by ursbraem** [comment]
> direkt auf die Rest API zugreifen

Ist sicher auch das Konsequenteste. Sollten wir dafür via Schule gehen, falls wir uns da einarbeiten?

> Wenn z.B. auf die Route /#getJsonData zugegriffen wird werden alle Events gemäss settings.js angezeigt 

das wäre die Luxusvariante

> oder alle ohne Rücksicht auf ein Konfiguration?

Geht auch. Wenn wir das JSON irgendwie kriegen, damit wir es per JS oder (fast lieber) PHP weiter"verwursten" können, können wir ja dann selber filtern. Es muss dann glaube ich ein XML werden, aber das betrifft Sie dann nicht mehr. Wir müssen einfach auf die Route zugreifen und die rohen Daten zum Weiterverarbeiten auslesen können. Falls das tatsächlich geht, würde ich sagen, lassen wir REST mal noch bleiben...

**Comment by schefbi** [comment]
> Ist sicher auch das Konsequenteste. Sollten wir dafür via Schule gehen, falls wir uns da einarbeiten?

Eigentlich nicht. Sie haben ja alle Informationen. Das einzige was Sie wohl machen müssen ist ein Offerte für die Umsetzung der BFF unterbreiten.

Mögliche Variante alle Events ohne Einschränkungen. Müsste noch der Link auf das Anmeldeformular bereitgestellt werden? Oder wie können sich Interessent auf "weiterbildung.swiss" anmelden?

/#getJsonData route könnte so aussehen:
https://jsonplaceholder.typicode.com/todos/

**Comment by ursbraem** [comment]
> Sie haben ja alle Informationen

Vom REST? Können Sie mir da nochmal den Entry-Point für die Doku geben?

> Müsste noch der Link auf das Anmeldeformular bereitgestellt werden?

Nicht zwingend, da wir diesen dank der "Perma-URL" auch selber konstruieren können. Die Kurs-ID reicht. Wenn wir Kurs 55926 haben machen wir daraus einfach https://www.bffbern.ch/wb/55926

> /#getJsonData route könnte so aussehen:

Ich würde am liebsten dies hier weiterverarbeiten:

![Screenshot-2020-05-10-at-21 47 58](https://user-images.githubusercontent.com/1446443/81509022-0d470100-9308-11ea-9001-5268600ec936.png)

**Comment by schefbi** [comment]
Wenn Sie nur das brauchen können Sie via Rest selber. Das was bei der BFF angezeigt wird kommt aus den Untenstehende Endpunkten. 

![image](https://user-images.githubusercontent.com/41326409/81645316-a9b4f480-9429-11ea-8d34-8d76f494c6f9.png)

**Comment by ursbraem** [comment]
Prima. REST it is. Bloss: wo finde ich die Doku zu REST? Ich habe bei Beginn der Arbeiten einmal eine Postman-Konfig erhalten. Aber es gibt da doch sicher einen offiziellen "Entry Point" mit allen Angaben? Brauche nur noch dies.

**Comment by schefbi** [comment]
Bitte melden Sie sich hierfür bei Ihrem Kunden. Das ist Sache des Auftraggebers. Hier geht es auch um Nutzungsvereinbarung...

**Comment by ursbraem** [comment]
Alles klar. Danke!
